const mongoose=require("mongoose");

const landlord=mongoose.Schema({
    landlordID:{
        type:Number,
        required:true,
        unique:true,
    },
    fname:{
        type:String,
        trim:true,
        required:true
    },
    lname:{
        type:String,
        trim:true,
        required:true
        
    },
    mobile:{
        type:String,
        trim:true,
        default:"",
    },
    baseRent:{
        type:Number,
        default:0,
    },
    water:{
        type:Number,
        default:0,
    },
    electricity:{
        type:Number,
        default:0,
    },
    security:{
        type:Number,
        default:0,
    },
    maintenance:{
        type:Number,
        default:0
    },
    createdON:{
        type:Date,
        //required:true,
        default:Date.now
    },
    address:{
        type:String,
        trim:true,
    },
    startRoom:{
        type:Number,
        default:0,
        //required:true,
        min:0
    },
    endRoom:{
        type:Number,
        default:0,
        //require:true,
        min:0
    },
    pswd:{
        type:String,
        required:true
    }
},
{ collection : 'landlord' }
)

mongoose.model('landlord',landlord);
module.exports=mongoose.model("landlord");