const mongoose=require("mongoose");

const tenant=mongoose.Schema({
    tenantID:{
        type:Number,
        min:0,
        unique:true,
        required:true
    },
    fname:{
        type:String,
        trim:true,
        required:true
    },
    lname:{
        type:String,
        trim:true,
        required:true
    },
    mobile:{
        type:String,
        unique:true,
        trim:true,
        default:""
    },
    email:{
        type:String,
        trim:true,
        required:true
    },
    room:{
        type:Number,
        min:0
    },
    verified:{
        type:Boolean,
        required:true
    },
    landlordID:{
        type:Number,
        min:0,
        required:true
    },
    idcreatedON:{
        type:Date,
        required:true,
        default:Date.now
    },
    allotON:{
        type:Date,
    },
    pswd:{
        type:String,
        required:true
    }
},
{ collection : 'tenant' }
);

mongoose.model('tenant',tenant);
module.exports=mongoose.model("tenant");