const mongoose=require("mongoose");

const transaction=mongoose.Schema({
    tid:{
        type:Number,
        required:true,
        unique:true,
        min:0
    },
    dateGenerated:{
        type:Date,
        default:Date.now,
        require:true
    },
    paidON:{
        type:Date,
    },
    amount:{
        type:Number,
        required:true,
        min:0
    },
    landlordID:{
        type:Number,
        required:true,
        min:0
    },
    tenantID:{
        type:Number,
        require:true,
        min:0
    },
    baseRent:{
        type:Number,
        require:true,
        min:0
    },
    water:{
        type:Number,
        require:true,
        min:0
    },
    electricity:{
        type:Number,
        require:true,
        min:0
    },
    maintenance:{
        type:Number,
        require:true,
        min:0
    },
    security:{
        type:Number,
        require:true,
        min:0
    },
    initialUnit:{
        type:Number,
        min:0,
    },
    finalUnit:{
        type:Number,
        min:0,
    },
    month:{
        type:Number
    },
    year:{
        type:Number
    }

},
{ collection : 'transaction' }
)

mongoose.model('transaction',transaction);
module.exports=mongoose.model("transaction");